Fix the crash caused by the key press
veeenu/hudhook pull request #175
Opened 2024-03-13 13:41 UTC by vSylva

https://github.com/veeenu/hudhook/issues/172

2024-03-13 19:10 UTC, veeenu requested changes
Save from the commented lines, looks good to me!

2024-03-13 19:10 UTC, veeenu commented on src/renderer/input.rs
> +    // event(RI_MOUSE_BUTTON_5_UP, MouseButton::Extra2, VK_XBUTTON2, false);
Could you please remove these?

2024-03-14 02:45 UTC, vSylva reviewed
Remove Comment https://github.com/veeenu/hudhook/pull/175#discussion_r1523791496

2024-03-14 03:56 UTC, vSylva commented on src/renderer/input.rs
> +    // event(RI_MOUSE_BUTTON_5_UP, MouseButton::Extra2, VK_XBUTTON2, false);
okie
done

2024-03-14 11:23 UTC, merged

2024-03-14 11:23 UTC, veeenu commented
Thank you!