Added tracing
veeenu/hudhook pull request #81
Opened 2023-03-12 14:39 UTC by Jakobzs

This PR aims to add `tracing` as a logger over `log` and `simplelog`. Still a WIP hence a draft.

2023-03-13 08:21 UTC, Godnoken commented
Out of curiosity, what is the purpose of this change?

2023-03-25 07:38 UTC, veeenu requested changes
Thank you for this! From a cursory check, it looks good in general, but I'd add logging in test/example modules. Haven't had a chance to test it but will do so soon.

2023-03-25 07:38 UTC, veeenu commented on tests/dx11.rs
> -
Can we add a tracing subscriber here? Seeing logs is pretty important for tests (same for other tests).

2023-03-25 07:38 UTC, veeenu commented on hudbook/hello-hud/Cargo.toml
> +hudhook = { version = "0.4.0", path = "../..", features = [] }
```suggestion
hudhook = { version = "0.4.0", path = "../.." }
```

2023-03-25 07:38 UTC, veeenu commented on examples/dx11_hook.rs
> -        hudhook::utils::simplelog();
Same as for the tests below -- can we add a tracing subscriber here?

2023-03-25 07:38 UTC, veeenu commented on Cargo.toml
> +# tracing-subscriber = "0.3"
I'd remove the `dev-dependencies` table entirely if we don't use any of its values; but we may need this anyway (see other comments)

2023-03-29 21:13 UTC, Jakobzs commented
Tracing subscribers should be added now.

2023-04-04 10:17 UTC, veeenu requested changes
I'm a bit scared because it took me quite a while to adapt one practice tool's code to work with tracing, so this will be quite the breaking change. But it seems like it also improved code quality somewhat and I prefer `tracing`'s approach. Once the two modifications I suggested are ready, we can merge.

2023-04-04 10:17 UTC, veeenu commented on src/lib.rs
> +        use tracing::*;
Could you reexport this like `log` was before, so it is made immediately available? I ran into this, because I didn't have `tracing` in my direct dependencies:

```
error[E0432]: unresolved import `tracing`
   --> lib\param-tinkerer\src\lib.rs:188:1
    |
188 | hudhook::hudhook!(ParamTinkerer::new().into_hook::<ImguiDx11Hooks>());
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `tracing`
    |
    = note: this error originates in the macro `hudhook::hudhook` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find macro `trace` in this scope
   --> lib\param-tinkerer\src\lib.rs:188:1
    |
188 | hudhook::hudhook!(ParamTinkerer::new().into_hook::<ImguiDx11Hooks>());
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `hudhook::hudhook` (in Nightly builds, run with -Z macro-backtrace for more info)```

2023-04-04 10:17 UTC, veeenu commented on src/lib.rs
```suggestion

pub use tracing;
```

2023-04-04 10:17 UTC, veeenu commented on src/lib.rs
> +        use tracing::*;
```suggestion
        use hudhook::tracing::*;
```

2023-04-04 12:21 UTC, Sages0ft commented on src/lib.rs
Done

2023-04-19 11:28 UTC, veeenu approved these changes

2023-04-19 11:29 UTC, merged

2023-04-23 14:05 UTC, Godnoken commented
> It is mainly to integrate a hugely more popular logging framework into hudhook.

Sorry for not getting back to this. Been crunching on my own stuff for a bit.

Interesting. Without having had a look at it - I assume I will no longer be able to see logs from hudhook from my own application if I stick to log and simplelog? I just implemented it a while ago and I'm quite content with it, but if not I'll have to change.

2023-04-23 14:26 UTC, veeenu commented
> Interesting. Without having had a look at it - I assume I will no longer be able to see logs from hudhook from my own application if I stick to log and simplelog? I just implemented it a while ago and I'm quite content with it, but if not I'll have to change.

Yep, that's correct. It's quite a big breaking change, but luckily the user facing API is almost 1:1 with tracing. Check [this PR](https://github.com/veeenu/eldenring-practice-tool/pull/46/files) out -- it looks big because it has other unrelated lints, but the change should be pretty small.

2023-04-23 15:17 UTC, Godnoken commented
Fair enough, I'll take a look. Cheers!