Fix OpenGL resizing
veeenu/hudhook pull request #95
Opened 2023-05-05 18:06 UTC by Godnoken

This PR will fix ImGui not resetting & thus disappearing in some games when a resize, resolution change or ALT + TAB happens.

We have to compare resolution because some older games (like CS 1.6) don't trigger any window resize when it is in fullscreen and the user changes resolution.

We have to compare window rect because ALT + TAB'ing and changing from windowed to/from fullscreen doesn't always trigger resolution change.

---

The only issue I have noticed so far is that after a bunch of resizes it is possible that everything ImGui renders goes completely black. If you resize again it is possible that it disappears.
I assume there is something more needed for the reset on the OpenGL end - maybe `glClearColor`?

![image](https://user-images.githubusercontent.com/17499594/236534577-f35d0e29-a3ef-4412-837d-73865bdb9142.png)

2023-05-05 18:55 UTC, Godnoken commented
Fixed everything turning black with `glClearColor`.

*Almost* tricked myself that it wasn't working because I kept rebuilding for x64 when the games I were trying it on are x86... 🤕

2023-05-07 18:15 UTC, veeenu requested changes

2023-05-07 18:15 UTC, veeenu commented on src/hooks/opengl3.rs
> +static mut RESOLUTION_AND_RECT: Option<Mutex<([i32; 2], RECT)>> = None;
I'd avoid adding global statics if possible. Global state is hard to track.

I think this instance could be added to the `ImguiRenderer` struct instead, skipping the mutex. The `reset` function could then be changed to lock `IMGUI_RENDERER`, pull this resolution data out of it, determine whether a clean needs to happen, then do a cleanup and finally `IMGUI_RENDERER.take()`. 

This flow is a bit more complicated, but it does catch a potential concurrency error where `IMGUI_RENDERER` is `None` but `cleanup` hasn't happened yet.

2023-05-10 13:00 UTC, Godnoken commented on src/hooks/opengl3.rs
> +static mut RESOLUTION_AND_RECT: Option<Mutex<([i32; 2], RECT)>> = None;
> I'd avoid adding global statics if possible. Global state is hard to track.

Agreed! Unfortunately, I am a terrible programmer in this aspect. Always struggling to find good ways to skip global variables.

> I think this instance could be added to the `ImguiRenderer` struct instead, skipping the mutex. The `reset` function could then be changed to lock `IMGUI_RENDERER`, pull this resolution data out of it, determine whether a clean needs to happen, then do a cleanup and finally `IMGUI_RENDERER.take()`.

> This flow is a bit more complicated, but it does catch a potential concurrency error where `IMGUI_RENDERER` is `None` but `cleanup` hasn't happened yet.

Great! I'll look into it, thank you for the example.

----

I noticed another annoying thing with some older games. For example, changing any setting in ~~CS 1.6~~ Stars Wars: KOTOR that isn't related to resolution _still_ "resets" the window and in those cases ImGui will stop rendering. I am not certain how this is solved, but it seems like Reshade does, as always.. Although as far as I understood, Reshade only checks the viewport for a change.

2023-05-14 21:36 UTC, veeenu approved these changes
LGTM! Looks clean and consistent now. We can merge into main after a rebase.

On an unrelated note, I just noticed that `IMGUI_RENDER` is an `Option<T>` instead of `OnceCell` -- I might want to change that to be more consistent across the board and to not accidentally run into concurrency issues (I'm not sure what could be some side effects of using one or the other, but I do know). Can't wait for [this](https://doc.rust-lang.org/std/sync/struct.OnceLock.html) to land into stable and do a pass over all of the other renderers too.

2023-05-15 06:27 UTC, Godnoken commented
> On an unrelated note, I just noticed that `IMGUI_RENDER` is an `Option<T>` instead of `OnceCell` -- I might want to change that to be more consistent across the board and to not accidentally run into concurrency issues (I'm not sure what could be some side effects of using one or the other, but I do know). Can't wait for [this](https://doc.rust-lang.org/std/sync/struct.OnceLock.html) to land into stable and do a pass over all of the other renderers too.

Yup, noticed that. There are quite a few inconsistencies across the renderers and hooks, not that it is surprising, but definitely may be worth looking at more closely.

Didn't even notice that OnceCell isn't thread-safe.

2023-05-15 09:59 UTC, merged

2023-05-15 10:03 UTC, veeenu commented
> Yup, noticed that. There are quite a few inconsistencies across the renderers and hooks, not that it is surprising, but definitely may be worth looking at more closely.

Yeah, now that I have quite a bit of experience with renderers and hooks under my belt I want to do a full refactor of all of that code eventually, likely once we're able to have more confidence in `windows-rs` again (as per my comments on #98).

> Didn't even notice that OnceCell isn't thread-safe.

It's not a big deal for us since currently we either use that with immutable data structures or wrap `Mutex`es in there, but the fewer data types the better, in my opinion, and switching to `OnceLock` is something I see as desirable eventually as then you don't have to manage that stuff manually.